import Navbar from '@/components/navbar'
import './globals.css'
import { Sacramento, Poppins} from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sacramento = Sacramento({ 
  weight: '400', 
  style: 'normal',
  subsets : ["latin"],
  variable:"--font-sac" 
})
const poppinsLight = Poppins({
  weight: '200',
  style: 'normal',
  subsets : ["latin"],
  variable:"--font-pop-light"
})

const poppinsMedium = Poppins({
weight: '500',
style: 'normal',
subsets : ["latin"],
variable:"--font-pop-medium"
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const fontClasses = `${sacramento.variable} ${poppinsLight.variable} ${poppinsMedium.variable}`;

  return (
    <html lang="en">
      <body className={`flex bg-white dark:bg-stone-950 ${fontClasses}`}>
        <div className='w-5 h-5 bg-slate-300 absolute rounded-full border-2 border-slate-500 opacity-40 transform translate-x-1/2 translate-y-1/2'></div>
        <Navbar/>
        <main className='flex w-screen h-screen justify-center items-center bg-white dark:bg-stone-950'>
        {children}
        </main> 
      </body>
    </html>
  )
}
